use serde::{Deserialize, Serialize};

/// Event types generated by sensors
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EventType {
    ProcessExec,
    NetworkConnection,
    FileAccess,
    Syscall,
}

/// Severity levels
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Severity {
    Low,
    Medium,
    High,
    Critical,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum EventDetails {
    ProcessExec {
        filename: String,
        args: Vec<String>,
        ppid: u32,
    },
    NetworkConnection {
        src_ip: String,
        dst_ip: String,
        src_port: u16,
        dst_port: u16,
        protocol: String,
    },
    FileAccess {
        path: String,
        operation: String,
        flags: u32,
    },
    Syscall {
        syscall_nr: u64,
        syscall_name: String,
        args: Vec<u64>,
    },
}

/// Security event detected by eBPF sensors
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityEvent {
    pub id: String,
    pub event_type: EventType,
    pub timestamp: u64,
    pub pid: u32,
    pub uid: u32,
    pub comm: String,
    pub details: EventDetails,
    pub severity: Severity,
}

impl SecurityEvent {
    /// helper constructor
    pub fn new(event_type: EventType, pid: u32, uid: u32, comm: String, details: EventDetails) -> Self {
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();

        let severity = Self::calculate_severity(&event_type, &details);
        SecurityEvent {
            id: uuid::Uuid::new_v4().to_string(),
            event_type,
            timestamp,
            pid,
            uid,
            comm,
            details,
            severity,
        }
    }

    fn calculate_severity(event_type: &EventType, details: &EventDetails) -> Severity {
        match (event_type, details) {
            (EventType::ProcessExec, EventDetails::ProcessExec { filename, .. }) => {
                if filename.contains("nc") || filename.contains("ncat") {
                    Severity::High
                } else {
                    Severity::Low
                }
            }
            (EventType::NetworkConnection, EventDetails::NetworkConnection { dst_port, .. }) => {
                if *dst_port == 4444 || *dst_port == 31337 {
                    Severity::Critical
                } else {
                    Severity::Medium
                }
            }
            (EventType::FileAccess, EventDetails::FileAccess { path, .. }) => {
                if path.contains("/etc/passwd") || path.contains("/etc/shadow") {
                    Severity::High
                } else {
                    Severity::Low
                }
            }
            _ => Severity::Low,
        }
    }
}
